<?php
/**
 * This file is part of Tricho and is copyright (C) Transmogrifier E-Solutions.
 * It is released under the GNU General Public License, version 3 or later.
 * See COPYRIGHT.txt and LICENCE.txt in the tricho directory for more details.
 */

namespace Tricho\DataUi;

use \DOMDocument;

abstract class FormModifier {
    /**
     * Supports manipulations to the form after it has been loaded
     * @param Form $form The form that this modifies
     */
    function postLoad(Form $form) {
    }
    
    
    /**
     * Supports manipulations to a Form and its values before generating HTML.
     * In particular, this allows hacking in default values for add forms
     * 
     * @param Form $form The form that this modifies
     * @param array &$values Values to include for the form fields
     * @param array &$errors The errors to display with the relevant fields
     * @param mixed $pk Null for add, array for edit
     * @return void
     */
    function preGenerate(Form $form, array &$values, array &$errors, $pk) {
    }
    
    
    /**
     * Supports manipulations on the DOMDocument generated by Form::generate.
     * @param Form $form The form that this modifies
     * @param DOMDocument $doc The document generated by Form::generate
     */
    function postGenerate(Form $form, DOMDocument $doc) {
    }
    
    
    /**
     * Supports custom validation that happens before the built-in validation.
     * N.B. at this point the source data ($_POST/$FILES) hasn't been collated,
     * so each of the array arguments will be empty.
     */
    function preValidate(Form $form, array &$source_data, array &$db_data, array &$errors) {
    }
    
    
    /**
     * Supports custom validation that happens after the built-in validation
     */
    function postValidate(Form $form, array &$source_data, array &$db_data, array &$errors) {
    }
    
    
    /**
     * @param array $data The data that was just put into the database
     * @param int $insert_id The autoincrement ID. Only applies for tables that
     *        have an autoincrement column, and only for add forms.
     * @param array $codes Any random presets that were generated by
     *        Form::process.
     */
    function postProcess(Form $form, array $data, $insert_id, array $codes) {
    }
}
